# Local GitLab CE lifecycle + the gitboard CLI.
#
# Everything here runs the code straight out of src/ via PYTHONPATH, and never
# through an editable install. On this machine a .pth-based editable install
# works for a few seconds after `pip install -e .` and then stops: the file is
# present and readable, its target exists, site lists it in the directory, and
# the path still is not added. Root cause unknown.
#
# What is reliable: naming src/ directly (PYTHONPATH), which is what every
# target below does. It also means edits are live with no reinstall.
# Do not "simplify" it away.

VENV       = .venv
PY         = $(VENV)/bin/python
PROJECT    ?=
SPEC       ?=
GITBOARD    = PYTHONPATH=src $(PY) -m gitboard.cli

.PHONY: help install activate link unlink up wait down reset logs seed show tui status snapshot report cron pull plan apply land test fmt lint docs clean stats digest

help:
	@grep -hE '^[a-z-]+:.*##' $(MAKEFILE_LIST) | sed 's/:.*##/\t/'

$(VENV)/bin/pytest: pyproject.toml
	python3 -m venv $(VENV)
	$(VENV)/bin/pip install -q --upgrade pip
	$(VENV)/bin/pip install -q ".[dev,docs]"
	@echo "installed into $(VENV)"

install: $(VENV)/bin/pytest  ## create .venv and install everything

activate:  ## open a subshell with .venv active (exit to leave)
	@test -x $(VENV)/bin/python || { \
	  echo "no $(VENV) here — run: make install" >&2; \
	  exit 1; }
	@echo "$(VENV) active — python, pytest, ruff, gitboard are on PATH."
	@echo "Type 'exit' to leave. (make cannot change your current shell, so"
	@echo "this is a subshell; 'source $(VENV)/bin/activate' does it in place.)"
	@VIRTUAL_ENV="$(CURDIR)/$(VENV)" \
	 PATH="$(CURDIR)/$(VENV)/bin:$$PATH" \
	 PYTHONPATH="$(CURDIR)/src" \
	 $$SHELL

link: install  ## put a `gitboard` command in ~/.local/bin (points back here)
	@mkdir -p $(HOME)/.local/bin
	@printf '#!/bin/sh\n# generated by `make link` in %s\nexec env PYTHONPATH=%s/src %s/$(VENV)/bin/python -m gitboard.cli "$$@"\n' \
	  "$(CURDIR)" "$(CURDIR)" "$(CURDIR)" > $(HOME)/.local/bin/gitboard
	@chmod +x $(HOME)/.local/bin/gitboard
	@echo "wrote $(HOME)/.local/bin/gitboard — runs src/ directly, so edits are live"

unlink:  ## remove that command again
	@rm -f $(HOME)/.local/bin/gitboard && echo "removed $(HOME)/.local/bin/gitboard"

up: .env  ## start the local GitLab container
	docker compose up -d

wait:  ## block until the container reports healthy (cold boot ~3-10 min)
	@until [ "$$(docker inspect -f '{{.State.Health.Status}}' gitlab 2>/dev/null)" = healthy ]; do \
	  docker inspect -f '{{.State.Running}}' gitlab >/dev/null 2>&1 || { echo "gitlab is not running — make up"; exit 1; }; \
	  printf '.'; sleep 10; \
	done; echo " healthy"

down:  ## stop the container, keep the data
	docker compose down

reset:  ## stop and wipe all three volumes
	docker compose down -v

logs:  ## follow container logs
	docker compose logs -f gitlab

seed: wait install  ## mint a PAT and apply boards/demo.yaml
	scripts/seed.py

show: install  ## print a board: make show PROJECT=group/project
	@$(GITBOARD) show $(PROJECT)

tui: install  ## the board, interactively: make tui PROJECT=group/project
	@$(GITBOARD) tui $(PROJECT)

snapshot: install  ## append board state to snapshots.jsonl: make snapshot PROJECT=group/project
	@$(GITBOARD) snapshot $(PROJECT)

report: install  ## what moved, from the snapshot log: make report PROJECT=group/project
	@$(GITBOARD) report $(PROJECT)

status: install  ## every local board YAML at a glance, no network
	@$(GITBOARD) status

cron:  ## print crontab lines: snapshots every 30 minutes, digests Monday 07:00
	@echo '*/30 * * * * cd $(CURDIR) && $(GITBOARD) snapshot --all >/dev/null 2>&1'
	@echo '0 7 * * 1 cd $(CURDIR) && $(GITBOARD) digest --all >/dev/null 2>&1'

stats: install  ## team numbers for one board, as markdown: make stats PROJECT=group/project
	@$(GITBOARD) stats $(PROJECT)

digest: install  ## write reports/<date>/<board>/{team,<user>}.md + .eml: make digest PROJECT=group/project
	@$(GITBOARD) digest $(PROJECT)

pull: install  ## save the board as YAML: make pull PROJECT=group/project
	@$(GITBOARD) pull $(PROJECT)

plan: install  ## preview YAML changes: make plan SPEC=boards/test.yaml
	@$(GITBOARD) plan $(SPEC)

apply: install  ## write the YAML to GitLab: make apply SPEC=boards/test.yaml
	@$(GITBOARD) apply $(SPEC)

land: install  ## apply, snapshot, refresh SPEC.base: make land SPEC=boards/test.yaml
	@$(GITBOARD) land $(SPEC)

test: install  ## run the test suite
	PYTHONPATH=src $(VENV)/bin/pytest -q

fmt: install  ## format (ruff format is black, same style)
	$(VENV)/bin/ruff format .

lint: install  ## lint, --fix to apply the safe fixes
	$(VENV)/bin/ruff check .

docs: install  ## build the HTML docs into docs/_build
	PYTHONPATH=src $(VENV)/bin/sphinx-build -W -b html docs docs/_build/html

.env:
	@echo "no .env — cp .env.example .env and set GITLAB_ROOT_PASSWORD" >&2; exit 1

clean:  ## remove venv, caches, and bytecode
	rm -rf $(VENV) .pytest_cache .ruff_cache docs/_build
	find . -name __pycache__ -not -path './$(VENV)/*' -exec rm -rf {} + 2>/dev/null || true
